name = "backend-del-tata" 
main = "worker.js"   # Archivo principal de tu Worker
compatibility_date = "2025-02-08"

# Configuración de la cuenta
account_id = "941c7578081b2ab8ee7836b33373b5da"

[vars]
GOOGLE_DRIVE_FOLDER_ID = "https://drive.google.com/drive/folders/1YOMFe6BxHD3tdvSLOxy5s5ztulIjMuwf"

node_compat = true